server:
  port: ${PORT:8873}
spring:
  profiles:
    active: dev
  application:
    name: storage-service
  messages:
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB