rootProject.name = "kotlin-spring-boot"
include("configuration")
include("common")
include("database")
include("service-gateway")
include("service-discovery")
include("service-auth")
include("service-storage")
include("service-user")
include("service-p2p")