server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
management:
  endpoints:
    web:
      exposure:
        include: "*"