server:
  port: 8762
spring:
  application:
    name: gateway
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    timeout: 60000
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 11000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
zuul:
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000
  # Disable accessing services using service name (i.e. gallery-service).
  # They should be only accessed through the path defined below.
  ignoredServices: '*'
  prefix: /api
  routes:
    auth-service:
      serviceId: auth-service
      path: /auth/**
    media-service:
      serviceId: storage-service
      path: /storage/**
    user-service:
      serviceId: user-service
      path: /user/**
  sensitive-headers: Cookie,Set-Cookie