server:
  port: 8762
spring:
  application:
    name: gateway
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    timeout: 60000
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000
  # Disable accessing services using service name (i.e. gallery-service).
  # They should be only accessed through the path defined below.
  ignoredServices: '*'
  prefix: /api
  routes:
    auth-service:
      serviceId: auth-service
      path: /auth/**
    media-service:
      serviceId: media-service
      path: /media/**
  sensitive-headers: Cookie,Set-Cookie