server:
  port: 8443
spring:
  thymeleaf:
    cache: false
  datasource:
    name: newbee-mall-datasource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vnapnic_schema?useSSL=false&useUnicode=true&characterEncoding=UTF8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    schema: classpath:database/schema.sql
    data: classpath:database/data.sql
    sql-script-encoding: UTF-8
    initialization-mode: always
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-secret: fDw7Mpkk5czHNuSRtmhGmAGL42CaxQB9
          client-id: R2dpxQ3vPrtfgF72
#  redis:
#    host: localhost
#    port: 6379
#    password: Your password
#  mail:
#    host: Your SMTP server like smtp.126.com
#    username: Your Email Address
#    password: Your password
#    default-encoding: UTF-8
#  jackson:
#    default-property-inclusion: NON_NULL

environment-params:
  verify-code-valid-seconds: 300 # 5 minutes
  verify-code-retry-max: 5 # 5 times/day
  web-client-id: vnapnicWeb
  web-client-secret: wtxTin9YdfVKhSHaD3OKOR/ygxu4Qu00TmqXVcSIaWQ
  web-client-scopes: User-WEB
  web-access-validity-seconds: 900 # 15 minutes
  web-refresh-validity-seconds: 432000 # 5 days
  mobile-client-id: vnapnicMobile
  mobile-client-secret: 46QYmEYLSwQAO7dg0vPPxZoSk6B9HcmjkqVm2gic3Yc
  mobile-client-scopes: User-MOBILE
  mobile-access-validity-seconds: 900 # 15 minutes
  mobile-refresh-validity-seconds: 259200 # 3 days
  visitor-client-id: MyFavoritesVisitor
  visitor-client-secret: rUEQUcfE3DsEImXWM7XL6u5dWYXyy6YPss7bN8MgstE
  visitor-client-scopes: Visitor-Restricted
  visitor-access-validity-seconds: 600 # 10 minutes
  visitor-refresh-validity-seconds: 0 # not allowed
  server-internal-id: vnapnicServer
  server-internal-secret: /mMulEUHjP7/IAa+xhHADVRM4sJwIFWteleFh6+M/wg