server:
  port: 8762
spring:
  application:
    name: gateway
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  # Disable accessing services using service name (i.e. gallery-service).
  # They should be only accessed through the path defined below.
  ignoredServices: '*'
  prefix: /api
  routes:
    user-service:
      serviceId: user-service
      path: /user/**