server:
  port: 8762
spring:
  application:
    name: gateway
  messages:
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    timeout: 60000
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  # Disable accessing services using service name (i.e. gallery-service).
  # They should be only accessed through the path defined below.
  ignoredServices: '*'
  prefix: /api
  routes:
    auth-service:
      serviceId: auth-service
      path: /auth/**
      filters:
        - name: CircuitBreaker
          args:
            name: auth-service
            fallbackuri: forward:/authFallBack
    storage-service:
      serviceId: storage-service
      path: /storage/**
    user-service:
      serviceId: user-service
      path: /user/**
      filters:
        - name: CircuitBreaker
          args:
            name: user-service
            fallbackuri: forward:/userFallBack
  sensitive-headers: Cookie,Set-Cookie

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
feign:
  histrix:
    enabled: false

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eager-load:
      enabled: true

auth-service:
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    eager-load:
      enabled: true
user-service:
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    eager-load:
      enabled: true

hystrix:
  command:
    choose:
      default:
        execution:
          timeout:
            enabled: false
          isolation:
            thread:
              timeoutInMilliseconds: 60000
      auth-service:
        execution:
          timeout:
            enabled: false
          isolation:
            thread:
              timeoutInMilliseconds: 60000
      user-service:
        execution:
          timeout:
            enabled: false
          isolation:
            thread:
              timeoutInMilliseconds: 60000