server:
  port: ${PORT:8762}

spring:
  profiles:
    active: dev
  application:
    name: gateway-service
  messages:
    encoding: UTF-8
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    timeout: 60000
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            #            allowedOrigins:
            #              - "*.ourdomain.com"
            #              - "*.ourotherdomain.com"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always