server:
  port: 8762
spring:
  application:
    name: gateway
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    timeout: 60000
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
            # Disable Hystrix timeout globally (for all services)
        timeout:
          enabled: false

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  # Disable accessing services using service name (i.e. gallery-service).
  # They should be only accessed through the path defined below.
  ignoredServices: '*'
  prefix: /api
  routes:
    auth-service:
      serviceId: auth-service
      path: /auth/**
      filters:
        - name: CircuitBreaker
          args:
            name: auth-service
            fallbackuri: forward:/authFallBack
    storage-service:
      serviceId: storage-service
      path: /storage/**
    user-service:
      serviceId: user-service
      path: /user/**
      filters:
        - name: CircuitBreaker
          args:
            name: user-service
            fallbackuri: forward:/userFallBack
  sensitive-headers: Cookie,Set-Cookie