server:
  port: 8762
spring:
  application:
    name: gateway
  messages:
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    timeout: 60000
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 5000

zuul:
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  # Disable accessing services using service name (i.e. gallery-service).
  # They should be only accessed through the path defined below.
  ignoredServices: '*'
  prefix: /api
  routes:
    auth-service:
      serviceId: auth-service
      path: /auth/**
      filters:
        - name: CircuitBreaker
          args:
            name: auth-service
            fallbackuri: forward:/authFallBack
    storage-service:
      serviceId: storage-service
      path: /storage/**
    user-service:
      serviceId: user-service
      path: /user/**
      filters:
        - name: CircuitBreaker
          args:
            name: user-service
            fallbackuri: forward:/userFallBack
  sensitive-headers: Cookie,Set-Cookie

#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream
#feign:
#  histrix:
#    enabled: false
#
#hystrix:
#  command:
#    choose:
#      default:
#        execution:
#          timeout:
#            enabled: false
            # Disable Hystrix timeout globally (for all services)
#    storage-service:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 960000
#  MaxAutoRetries: 1 # Number of retries for the current instance
#  MaxAutoRetriesNextServer: 1 # Number of retries for switching instances

#storage-service:
#  ribbon:
#    ConnectTimeout: 960000
#    ReadTimeout: 960000
#    MaxAutoRetries: 1 # Number of retries for the current instance
#    MaxAutoRetriesNextServer: 1 # Number of retries for switching instances
