eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8765
spring:
  application:
    name: peoples-service
#server:
#  port: 1431
#spring:
#  application:
#    name: user-service
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/vnapnic_schema
#    username: root
#    password: 123456
#  jpa:
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#  session:
#    jdbc:
#      initialize-schema: always
#  jackson:
#    default-property-inclusion: NON_NULL
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:10000/eureka/